jwt-key: cmFtZG9ta2V5aXNyYW5kb21yYW1kb21rZXlpc3JhbmRvbXJhbWRvbWtleWlzcmFuZG9t

server:
  port: 8091

management:
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: "http://localhost:8081"
          predicates:
            - Path=/auth/**
        - id: user
          uri: "http://localhost:8080"
          predicates:
            - Path=/user/**
